#include "builder_local.h"

#include "core/include/paths.h"
#include "core/include/string_helpers.h"
#include "core/include/file.h"
#include "core/include/debug.h"
#include "core/include/string_builder.h"

bool8 GenerateZedJSONFiles( buildContext_t *context, BuilderOptions *options ) {
	const char *dotZedFolder = tprintf( "%s%c.zed", context->inputFilePath.data, PATH_SEPARATOR );

	if ( !folder_create_if_it_doesnt_exist( dotZedFolder ) ) {
		error( "Failed to create .zed folder at \"%s\".\n", context->inputFilePath.data );
		return false;
	}

	const char *builderPath = options->zedJSONOptions.builderPath.empty() ? BUILDER_PROGRAM_NAME : options->zedJSONOptions.builderPath.c_str();

	// tasks.json
	{
		const char *tasksJSONFilename = tprintf( "%s%ctasks.json", dotZedFolder, PATH_SEPARATOR );

		StringBuilder tasksJSONContent = {};
		defer( string_builder_destroy( &tasksJSONContent ) );

		string_builder_reset( &tasksJSONContent );

		string_builder_appendf( &tasksJSONContent, "// Project tasks configuration. See https://zed.dev/docs/tasks for documentation.\n" );
		string_builder_appendf( &tasksJSONContent, "// This file was generated by Builder.\n" );
		string_builder_appendf( &tasksJSONContent, "[\n" );
		For ( u32, configIndex, 0, options->zedJSONOptions.taskConfigs.size() ) {
			ZedTaskConfig *taskConfig = &options->zedJSONOptions.taskConfigs[configIndex];

			string_builder_appendf( &tasksJSONContent, "\t{\n" );
			string_builder_appendf( &tasksJSONContent, "\t\t\"label\": \"Build %s\"\n", taskConfig->config.name.c_str() );
			string_builder_appendf( &tasksJSONContent, "\t\t\"command\": \"%s %s%s\"\n", builderPath );
			string_builder_appendf( &tasksJSONContent, "\t\t\"args\": [\n" );
			string_builder_appendf( &tasksJSONContent, "\t\t\t\"%s\"", context->inputFile );
			string_builder_appendf( &tasksJSONContent, "\t\t\t\"%s%s\"", ARG_CONFIG, taskConfig->config.name.c_str() );
			For ( u32, argIndex, 0, taskConfig->args.size() ) {
				string_builder_appendf( &tasksJSONContent, "\t\t\t\"%s\"", taskConfig->args[argIndex].c_str() );

				if ( argIndex < taskConfig->args.size() - 1 ) {
					string_builder_appendf( &tasksJSONContent, "," );
				}

				string_builder_appendf( &tasksJSONContent, "\n" );
			}
			string_builder_appendf( &tasksJSONContent, "\t\t\"]\n" );
			string_builder_appendf( &tasksJSONContent, "\t}" );

			if ( configIndex < options->zedJSONOptions.taskConfigs.size() - 1 ) {
				string_builder_appendf( &tasksJSONContent, "," );
			}

			string_builder_appendf( &tasksJSONContent, "\n" );
		}
		string_builder_appendf( &tasksJSONContent, "]\n" );

		if ( !WriteStringBuilderToFile( &tasksJSONContent, tasksJSONFilename ) ) {
			error( "Failed to write \"%s\".\n", tasksJSONFilename );
			return false;
		}
	}

	// debug.json
	{
		const char *debugJSONFilename = tprintf( "%s%cdebug.json", dotZedFolder, PATH_SEPARATOR );

		StringBuilder debugJSONContent = {};
		defer( string_builder_destroy( &debugJSONContent ) );

		string_builder_reset( &debugJSONContent );

		string_builder_appendf( &debugJSONContent, "// Project-local debug tasks\n" );
		string_builder_appendf( &debugJSONContent, "//\n" );
		string_builder_appendf( &debugJSONContent, "// For more documentation on how to configure debug tasks,\n" );
		string_builder_appendf( &debugJSONContent, "// see: https://zed.dev/docs/debugger\n" );
		string_builder_appendf( &debugJSONContent, "// This file was generated by Builder\n" );
		string_builder_appendf( &debugJSONContent, "[\n" );
		For ( u32, i, 0, options->zedJSONOptions.debugConfigs.size() ) {
			string_builder_appendf( &debugJSONContent, "\t{\n" );
			// string_builder_appendf( &debugJSONContent, "\t\t\n" );
			// TODO(DM): carry on here
			string_builder_appendf( &debugJSONContent, "\t}\n" );
		}
		string_builder_appendf( &debugJSONContent, "]\n" );

		if ( !WriteStringBuilderToFile( &debugJSONContent, debugJSONFilename ) ) {
			error( "Failed to write \"%s\".\n", debugJSONFilename );
			return false;
		}
	}
}